#두 정수를 입력받아 사칙연산 결과를 출력 
a= int(input("첫 번째 숫자 : "))
b= int(input("두 번째 숫자 : "))
print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"/",b,"=",a/b)

a=int(input("첫 번째 숫자"))
b=int(input("두 번째 숫자"))
print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"/",b,"=",a/b)

a=int(input("첫 번째 숫자: "))
b=int(input("두 번째 숫자: "))
print(a,"+",b,"=",a+b)
print(a,"-",b,"=",a-b)
print(a,"*",b,"=",a*b)
print(a,"/",b,"=",a/b)
